# DeePMD-enabled GPUMD

.DEFAULT_GOAL := gpumd

DEEPMD_ROOT ?= /root/data/conda_data/envs/dpmd2

include makefile

# Enable DeePMD interface
CFLAGS += -DUSE_DEEPMD

# DeepPot.h is located at:
# $(DEEPMD_ROOT)/include/deepmd/DeepPot.h
INC += -I$(DEEPMD_ROOT)/include/deepmd

# DeePMD C/C++ libraries
LIBS += $(DEEPMD_ROOT)/lib/libdeepmd_cc.so
LIBS += $(DEEPMD_ROOT)/lib/libdeepmd_c.so

# GPUMD is finally linked by nvcc, so use -Xlinker
# to embed DeePMD runtime path.
LIBS += -Xlinker=-rpath -Xlinker=$(DEEPMD_ROOT)/lib